//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorJS.CalculatorJS {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class CalculatorJS {
        
        public static implicit operator global::System.Web.UI.TemplateControl(CalculatorJS target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::CalculatorJS.CalculatorJS.CalculatorJS @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<link href=\"../_layouts/15/CalculatorJS/view.css\" rel=\"stylesheet\" />\r\n<div id=" +
                        "\"container\">\r\n        <div id=\"container2\">\r\n            <div id=\"calculator\" cl" +
                        "ass=\"calc\">\r\n                <!-- Screen and clear key -->\r\n                <div" +
                        " class=\"top\">\r\n                    <span class=\"clear\">C</span>\r\n               " +
                        "     <div class=\"screen\"></div>\r\n                </div>\r\n\r\n                <div " +
                        "class=\"keys\">\r\n                    <!-- operators and other keys -->\r\n          " +
                        "          <span>7</span>\r\n                    <span>8</span>\r\n                  " +
                        "  <span>9</span>\r\n                    <span class=\"operator\">Del</span>\r\n       " +
                        "             <span>4</span>\r\n                    <span>5</span>\r\n               " +
                        "     <span>6</span>\r\n                    <span class=\"operator\">+</span>\r\n      " +
                        "              <span>1</span>\r\n                    <span>2</span>\r\n              " +
                        "      <span>3</span>\r\n                    <span class=\"operator\">-</span>\r\n     " +
                        "               <span>0</span>\r\n                    <span>.</span>\r\n             " +
                        "       <span class=\"eval\">=</span>\r\n                    <span class=\"operator\">/" +
                        "</span>\r\n\r\n                    <span>Sin</span>\r\n                    <span>Cos</" +
                        "span>\r\n                    <span>Tan</span>\r\n                    <span class=\"op" +
                        "erator\">x</span>\r\n                </div>\r\n            </div>\r\n        </div>\r\n  " +
                        "  </div>\r\n    <!-- PrefixFree -->\r\n    <script src=\"http://thecodeplayer.com/upl" +
                        "oads/js/prefixfree-1.0.7.js\" type=\"text/javascript\"></script>\r\n    <script src=\"" +
                        "../_layouts/15/CalculatorJS/logic.js\" type=\"text/javascript\"></script>"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
